# Generated by Django 4.1.7 on 2023-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='owner',
            name='payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
