# Generated by Django 4.1.7 on 2023-05-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_delete_category_owner_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdCoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('razor_payment_id', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
