# Generated by Django 4.1.7 on 2023-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_rename_paid_coldcoffeeshop_payment_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcoffeeshop',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coldcoffeeshop',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
