# Generated by Django 4.1.7 on 2023-05-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_coldcoffeeshop_payment_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='razor_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
