# Generated by Django 4.1.7 on 2023-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_alter_coldcoffeeshop_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcoffeeshop',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coldcoffeeshop',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
