# Generated by Django 4.1.7 on 2023-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_alter_coldcoffeeshop_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcoffeeshop',
            name='return_amt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coldcoffeeshop',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
