# Generated by Django 4.1.7 on 2023-05-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_coldcoffeeshop_return_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='ColdCoffeeShop',
            new_name='Customer',
        ),
    ]
