# Generated by Django 4.1.7 on 2023-05-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_website_ac_rename_coldcoffeeshop_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='return_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='website_ac',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
