# Generated by Django 4.1.7 on 2023-05-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0013_alter_customer_amount_alter_customer_return_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='return_amt',
            field=models.IntegerField(null=True),
        ),
    ]
