# Generated by Django 4.1.7 on 2023-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0015_alter_customer_mobile_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='return_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='website_ac',
            name='amount',
            field=models.FloatField(),
        ),
    ]
